# Local Environment
# Lab 02: Distributed Systems

info:
  name: Local Environment
  schema: https://schema.getpostman.com/json/collection/v2.1.0/environment.json

variable:
  # Gateway Microservice
  - key: gateway_base_url
    value: "http://localhost:8080"
    type: string
  
  # Flight Microservice
  - key: flight_base_url
    value: "http://localhost:8060"
    type: string
  
  # Ticket Microservice
  - key: ticket_base_url
    value: "http://localhost:8070"
    type: string
  
  # Bonus Microservice
  - key: bonus_base_url
    value: "http://localhost:8050"
    type: string
